### ISSUE TITLE
Add a unique sequential number to each idea

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/diverge#10]
Might as well start at 1. A zero based number system would just confuse people. 

The number could appear in the bottom right of the card, or wherever it fits well. It doesn't need to be large.

**Comment by drewsdunne** [comment]
Is it good to just have a number in the corner? You don't want any label identifying what the number is?

**Comment by andyburnett** [comment]
I think the meaning of the number will be pretty clear once a few ideas have been entered. If it is possible to put the number in a box or some other device to visually set it aside from the text

**Comment by drewsdunne** [comment]
Yeah I can make that work
