### ISSUE TITLE
Make comments look like comments

### ISSUE THREAD

**Issue by drewsdunne** [Knowinnovation/diverge#14]
They look kinda funny, I don't know if we want to number them or something. Also I couldn't order them.

**Comment by drewsdunne** [comment]
They look kinda funny, I don't know if we want to number them or something. Also I couldn't order them.

**Comment by andyburnett** [comment]
I have a few suggestions

1. I think we should remove the date object from the card. It probably takes too much space, and as long as the cards are sequentially numbered it shouldn't be a problem. 

2. The text - in an iPhone - is still too light. I think it needs to be black

3. The show/hide comment link should probably say "add comment" when their are no comments.

**Comment by drewsdunne** [comment]
Alright I can remove it. 

I don't know what's up with that its black on the computer and should be the same. 

And the add comment thing doesn't make too much sense because what that button does is show/hide the comments sections, it doesn't add comments.

**Comment by andyburnett** [comment]
Ah, good point re the comments. OK, lets think about it a bit more.
